kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: core-api
spec:
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: core-api
          image: mlposey/core
          ports:
            - containerPort: 8080
          env:
            - name: SQL_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: host
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user
            - name: SQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: client-id