kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: core-api
spec:
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: core-api
          image: mlposey/core
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: database-secret
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: client-id