apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: logt
spec:
  selector:
    matchLabels:
      app: logt
  template:
    metadata:
      labels:
        app: logt
    spec:
      volumes:
        - name: aws-credstore
          secret:
            secretName: sns-creds
      imagePullSecrets:
        - name: regcred
      containers:
        - name: logt
          image: mlposey/logt:0.2.1
          volumeMounts:
            - name: aws-credstore
              mountPath: /root/.aws
          envFrom:
            - configMapRef:
                name: logt-config
            - secretRef:
                name: redis-secret
            - secretRef:
                name: elastic-secret
            - secretRef:
                name: sns-secret
